### ISSUE TITLE
pyproj issue

### ISSUE THREAD

**Issue by NO645** [kvos/CoastSat#125]
Ever since the new GE update when I install a new CoastSat environment it works a few times and then starts having the error below. This occurs after I have defined a reference shoreline and apparently before it saves that shoreline to the geojson file. Reinstalling a new environment and the CoastSat package fixes things for a few uses and then it seems to return to this behavior.

Thank you for any thoughts or suggestions.

QTimer::singleShot: Timers cannot have negative timeouts

QTimer::singleShot: Timers cannot have negative timeouts
QTimer::singleShot: Timers cannot have negative timeouts
Traceback (most recent call last):

  File "C:\Users\user\Desktop\wave2014\example3.py", line 216, in <module>
    settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)

  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\coastsat_08_12_2020\lib\site-packages\coastsat\SDS_preprocess.py", line 886, in get_reference_sl
    gdf_all = gdf_all.to_crs({'init': 'epsg:'+str(settings['output_epsg'])})

  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\coastsat_08_12_2020\lib\site-packages\geopandas\geodataframe.py", line 443, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)

  File "C:\Users\v\AppData\Local\Continuum\anaconda3\envs\coastsat_08_12_2020\lib\site-packages\geopandas\geoseries.py", line 304, in to_crs
    proj_in = pyproj.Proj(self.crs, preserve_units=True)

  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\coastsat_08_12_2020\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)

  File "_proj.pyx", line 129, in _proj.Proj.__cinit__

RuntimeError: b'no arguments in initialization list'

**Comment by kvos** [comment]
that's an issue with the GDAL environment I would say, I am not sure how to fix this as it is probably a conflict between packages.
Try to clean your environment and re-install. Before re-installing run 
 `conda clean --all`

what epsg code are you using?

**Comment by NO645** [comment]
I was using your NARRA example with EPSG 28356.

I ran conda clean and tried again before rebuilding the environment. That seemed to work. If it fails again I'll try cleaning and rebuilding but I'm happy with this solution. Rebuilding takes me some time since I like to make some aesthetic modifications to the plots.

Thank you!
