### ISSUE TITLE
Value Error while Mapping the shorelines

### ISSUE THREAD

**Issue by MeghanaKavuri** [kvos/CoastSat#163]
Hi Vos, 
This is Meghana, while i was mapping the shorelines for L5 and L8, a valueError is occuring after mapping upto 35% in L8.

**L8:   35%Traceback (most recent call last):
  File "43.py", line 99, in <module>
    output = SDS_shoreline.extract_shorelines(metadata, settings)
  File "/home/meghana/Desktop/CoastSat-master/coastsat/SDS_shoreline.py", line 163, in extract_shorelines
    min_beach_area_pixels, clf)
  File "/home/meghana/Desktop/CoastSat-master/coastsat/SDS_shoreline.py", line 354, in classify_image_NN
    labels = clf.predict(vec_features)
  File "/home/meghana/anaconda3/envs/coastsat/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py", line 953, in predict
    y_pred = self._predict(X)
  File "/home/meghana/anaconda3/envs/coastsat/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py", line 658, in _predict
    X = check_array(X, accept_sparse=['csr', 'csc', 'coo'])
  File "/home/meghana/anaconda3/envs/coastsat/lib/python3.7/site-packages/sklearn/utils/validation.py", line 573, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/meghana/anaconda3/envs/coastsat/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').**

**And also while mapping the shorelines, in every image the shoreline is not properly detected where it is also detecting the other land features as the shoreline. I will attach the image where the shoreline is detected wrong. And in some cases, the image gets cut, while mapping the shoreline.
![1988-11-20-04-29-54_L5](https://user-images.githubusercontent.com/67146836/102210141-ce110c00-3ef7-11eb-88a3-b8632f9f2c15.jpg)

![2014-03-01-04-59-56_L8](https://user-images.githubusercontent.com/67146836/102210478-3d86fb80-3ef8-11eb-8ec6-5346bd73c68f.jpg)

**Comment by MeghanaKavuri** [comment]
Hi Vos, Can you please help why the above error is popping up?

**Comment by kvos** [comment]
I don't know why there is a value error. You can limit the mapped shoreline to only points that are along a reference shoreline that you digitise beforehand.

**Comment by MeghanaKavuri** [comment]
Even If I give the reference shoreline, I am getting the below error.

![error](https://user-images.githubusercontent.com/67146836/106422049-e62af380-6483-11eb-909d-a60783588aad.png)
