### ISSUE TITLE
Download failing on L7

### ISSUE THREAD

**Issue by Lvulis** [kvos/CoastSat#311]
I'm using a slightly old version of the notebook and just downloaded the latest copy of the main branch, got this error twice over a box around southern California. Don't see any apparent changes in the actual python functions being called, so not sure if its a notebook issue or a backend issue.
```python
># inputs['include_T2'] = True
> metadata = SDS_download.retrieve_images(inputs)
Number of images available between 1984-01-01 and 2021-12-31:
- In Landsat Tier 1 & Sentinel-2 Level-1C:
     L5: 481 images
     L7: 480 images
     L8: 194 images
     S2: 795 images
  Total to download: 1950 images
- In Landsat Tier 2 (not suitable for time-series analysis):
     L5: 34 images
     L7: 391 images
     L8: 359 images
  Total Tier 2: 784 images

Downloading images:
L5: 481 images
100%
L7: 480 images
66%Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "~\.conda\envs\coastsat\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "~\AppData\Local\Temp\ipykernel_12136\3756769406.py", line 2, in <cell line: 2>
    metadata = SDS_download.retrieve_images(inputs)
  File "~\Documents\beaches\CoastSat\coastsat\SDS_download.py", line 241, in retrieve_images
  File "~\Documents\beaches\CoastSat\coastsat\SDS_download.py", line 680, in download_tif
    local_zipfile.extract(fn, filepath)
  File "~\.conda\envs\coastsat\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "~\.conda\envs\coastsat\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~\.conda\envs\coastsat\lib\site-packages\IPython\core\interactiveshell.py", line 1992, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "~\.conda\envs\coastsat\lib\site-packages\IPython\core\ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "~\.conda\envs\coastsat\lib\site-packages\IPython\core\ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "~\.conda\envs\coastsat\lib\site-packages\IPython\core\ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "~\.conda\envs\coastsat\lib\site-packages\IPython\core\ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "~\.conda\envs\coastsat\lib\site-packages\IPython\core\ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "~\.conda\envs\coastsat\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "~\.conda\envs\coastsat\lib\site-packages\stack_data\core.py", line 698, in lines
    pieces = self.included_pieces
  File "~\.conda\envs\coastsat\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "~\.conda\envs\coastsat\lib\site-packages\stack_data\core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "~\.conda\envs\coastsat\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "~\.conda\envs\coastsat\lib\site-packages\stack_data\core.py", line 628, in executing_piece
    return only(
  File "~\.conda\envs\coastsat\lib\site-packages\executing\executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```

**Comment by Lvulis** [comment]
Just an update this seems to be an issue arising from specific landsat image but I don't know which specific one. The last one I have that was valid is 2014-08-21-18-20-10_L7_OS_new_1_pan.tif, the next one was invalid. This is the region of interest
```python
polygon = [[[-117.299433,32.884307],
            [-117.222455,32.8912],
            [-117.23261,32.756019],
            [-117.319059,33.055662],
            [-117.285505,32.752007]]] 
```

**Comment by kvos** [comment]
hi @Lvulis , make sure yo ustart in a new data folder so that you are not mixing up downloads from the previous and new versions of coastsat. I'm also still investigating issue #301 which could be related to this one

**Comment by kvos** [comment]
![image](https://user-images.githubusercontent.com/7217258/183881582-2aa1c78a-f178-4fec-9ca9-ff59dd43b5c7.png)

it seems like there is a corrupted zip file that sneaks in and crashed the code

**Comment by Lvulis** [comment]
Hi @kvos, I cloned your repo directly in one directory and saved a semi-previous version of coastsat in a separate directory to try and avoid issues. My labmate is getting the same errors now.

I will get it reproduced but I had again issues with read/write of data in another region, with numerous connection timeouts to GEE (and the whole download crashing) &/or read/write access failure. Will update the issue accordingly. My hypothesis is that the corrupted zip file is occurring due to connection intermittency and not actually corrupted data coming from GEE.

**Comment by kvos** [comment]
ok I also ran into that corrupted zip file error, tried to open it on windows and it said it was unable to unzip it. It's probably a connection timeout issue. I can wrap the function call up in an infinite loop with try/except so that it just tries until it gets a sound zip file

**Comment by Lvulis** [comment]
Timeout error for the record:
```Python
Number of images available between 1984-01-01 and 2021-12-31:
- In Landsat Tier 1 & Sentinel-2 Level-1C:
     L5: 906 images
     L7: 907 images
     L8: 368 images
     S2: 830 images
  Total to download: 3011 images
- In Landsat Tier 2 (not suitable for time-series analysis):
     L5: 70 images
     L7: 59 images
     L8: 181 images
  Total Tier 2: 310 images

Downloading images:
L5: 906 images
100%
L7: 907 images
47%
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
File ~\.conda\envs\coastsat\lib\site-packages\urllib3\connectionpool.py:703, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    702 # Make the request on the httplib connection object.
--> 703 httplib_response = self._make_request(
    704     conn,
    705     method,
    706     url,
    707     timeout=timeout_obj,
    708     body=body,
    709     headers=headers,
    710     chunked=chunked,
    711 )
    713 # If we're going to release the connection in ``finally:``, then
    714 # the response doesn't need to know about the connection. Otherwise
    715 # it will also try to release it and we'll have a double-release
    716 # mess.

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\connectionpool.py:386, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    385 try:
--> 386     self._validate_conn(conn)
    387 except (SocketTimeout, BaseSSLError) as e:
    388     # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\connectionpool.py:1040, in HTTPSConnectionPool._validate_conn(self, conn)
   1039 if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1040     conn.connect()
   1042 if not conn.is_verified:

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\connection.py:414, in HTTPSConnection.connect(self)
    412     context.load_default_certs()
--> 414 self.sock = ssl_wrap_socket(
    415     sock=conn,
    416     keyfile=self.key_file,
    417     certfile=self.cert_file,
    418     key_password=self.key_password,
    419     ca_certs=self.ca_certs,
    420     ca_cert_dir=self.ca_cert_dir,
    421     ca_cert_data=self.ca_cert_data,
    422     server_hostname=server_hostname,
    423     ssl_context=context,
    424     tls_in_tls=tls_in_tls,
    425 )
    427 # If we're using all defaults and the connection
    428 # is TLSv1 or TLSv1.1 we throw a DeprecationWarning
    429 # for the host.

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\util\ssl_.py:449, in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)
    448 if send_sni:
--> 449     ssl_sock = _ssl_wrap_socket_impl(
    450         sock, context, tls_in_tls, server_hostname=server_hostname
    451     )
    452 else:

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\util\ssl_.py:493, in _ssl_wrap_socket_impl(sock, ssl_context, tls_in_tls, server_hostname)
    492 if server_hostname:
--> 493     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
    494 else:

File ~\.conda\envs\coastsat\lib\ssl.py:500, in SSLContext.wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    494 def wrap_socket(self, sock, server_side=False,
    495                 do_handshake_on_connect=True,
    496                 suppress_ragged_eofs=True,
    497                 server_hostname=None, session=None):
    498     # SSLSocket class handles server_hostname encoding before it calls
    499     # ctx._wrap_socket()
--> 500     return self.sslsocket_class._create(
    501         sock=sock,
    502         server_side=server_side,
    503         do_handshake_on_connect=do_handshake_on_connect,
    504         suppress_ragged_eofs=suppress_ragged_eofs,
    505         server_hostname=server_hostname,
    506         context=self,
    507         session=session
    508     )

File ~\.conda\envs\coastsat\lib\ssl.py:1040, in SSLSocket._create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1039             raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1040         self.do_handshake()
   1041 except (OSError, ValueError):

File ~\.conda\envs\coastsat\lib\ssl.py:1309, in SSLSocket.do_handshake(self, block)
   1308         self.settimeout(None)
-> 1309     self._sslobj.do_handshake()
   1310 finally:

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

ProtocolError                             Traceback (most recent call last)
File ~\.conda\envs\coastsat\lib\site-packages\requests\adapters.py:489, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    488 if not chunked:
--> 489     resp = conn.urlopen(
    490         method=request.method,
    491         url=url,
    492         body=request.body,
    493         headers=request.headers,
    494         redirect=False,
    495         assert_same_host=False,
    496         preload_content=False,
    497         decode_content=False,
    498         retries=self.max_retries,
    499         timeout=timeout,
    500     )
    502 # Send the request.
    503 else:

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\connectionpool.py:785, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    783     e = ProtocolError("Connection aborted.", e)
--> 785 retries = retries.increment(
    786     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    787 )
    788 retries.sleep()

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\util\retry.py:550, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    549 if read is False or not self._is_method_retryable(method):
--> 550     raise six.reraise(type(error), error, _stacktrace)
    551 elif read is not None:

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\packages\six.py:769, in reraise(tp, value, tb)
    768 if value.__traceback__ is not tb:
--> 769     raise value.with_traceback(tb)
    770 raise value

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\connectionpool.py:703, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    702 # Make the request on the httplib connection object.
--> 703 httplib_response = self._make_request(
    704     conn,
    705     method,
    706     url,
    707     timeout=timeout_obj,
    708     body=body,
    709     headers=headers,
    710     chunked=chunked,
    711 )
    713 # If we're going to release the connection in ``finally:``, then
    714 # the response doesn't need to know about the connection. Otherwise
    715 # it will also try to release it and we'll have a double-release
    716 # mess.

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\connectionpool.py:386, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    385 try:
--> 386     self._validate_conn(conn)
    387 except (SocketTimeout, BaseSSLError) as e:
    388     # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\connectionpool.py:1040, in HTTPSConnectionPool._validate_conn(self, conn)
   1039 if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1040     conn.connect()
   1042 if not conn.is_verified:

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\connection.py:414, in HTTPSConnection.connect(self)
    412     context.load_default_certs()
--> 414 self.sock = ssl_wrap_socket(
    415     sock=conn,
    416     keyfile=self.key_file,
    417     certfile=self.cert_file,
    418     key_password=self.key_password,
    419     ca_certs=self.ca_certs,
    420     ca_cert_dir=self.ca_cert_dir,
    421     ca_cert_data=self.ca_cert_data,
    422     server_hostname=server_hostname,
    423     ssl_context=context,
    424     tls_in_tls=tls_in_tls,
    425 )
    427 # If we're using all defaults and the connection
    428 # is TLSv1 or TLSv1.1 we throw a DeprecationWarning
    429 # for the host.

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\util\ssl_.py:449, in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)
    448 if send_sni:
--> 449     ssl_sock = _ssl_wrap_socket_impl(
    450         sock, context, tls_in_tls, server_hostname=server_hostname
    451     )
    452 else:

File ~\.conda\envs\coastsat\lib\site-packages\urllib3\util\ssl_.py:493, in _ssl_wrap_socket_impl(sock, ssl_context, tls_in_tls, server_hostname)
    492 if server_hostname:
--> 493     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
    494 else:

File ~\.conda\envs\coastsat\lib\ssl.py:500, in SSLContext.wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    494 def wrap_socket(self, sock, server_side=False,
    495                 do_handshake_on_connect=True,
    496                 suppress_ragged_eofs=True,
    497                 server_hostname=None, session=None):
    498     # SSLSocket class handles server_hostname encoding before it calls
    499     # ctx._wrap_socket()
--> 500     return self.sslsocket_class._create(
    501         sock=sock,
    502         server_side=server_side,
    503         do_handshake_on_connect=do_handshake_on_connect,
    504         suppress_ragged_eofs=suppress_ragged_eofs,
    505         server_hostname=server_hostname,
    506         context=self,
    507         session=session
    508     )

File ~\.conda\envs\coastsat\lib\ssl.py:1040, in SSLSocket._create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1039             raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1040         self.do_handshake()
   1041 except (OSError, ValueError):

File ~\.conda\envs\coastsat\lib\ssl.py:1309, in SSLSocket.do_handshake(self, block)
   1308         self.settimeout(None)
-> 1309     self._sslobj.do_handshake()
   1310 finally:

ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
Input In [3], in <cell line: 2>()
      1 # inputs['include_T2'] = True
----> 2 metadata = SDS_download.retrieve_images(inputs)

File ~\Documents\beaches\CoastSat\coastsat\SDS_download.py:239, in retrieve_images(inputs)
    236 ee_region_pan = adjust_polygon(inputs['polygon'],proj_pan)
    238 # download both ms and pan bands from EE
--> 239 fn_ms, fn_QA = download_tif(image_ee,ee_region_ms,bands['ms'],fp_ms)
    240 fn_pan = download_tif(image_ee,ee_region_pan,bands['pan'],fp_pan)
    242 # create filename for both images (ms and pan)

File ~\Documents\beaches\CoastSat\coastsat\SDS_download.py:673, in download_tif(image, polygon, bands, filepath)
    665 # for the newer versions of ee
    666 else:       
    667     # crop and download
    668     download_id = ee.data.getDownloadId({'image': image,
    669                                          'region': polygon,
    670                                          'bands': bands,
    671                                          'filePerBand': True,
    672                                          'name': 'image'})
--> 673     response = requests.get(ee.data.makeDownloadUrl(download_id))  
    674     fp_zip = os.path.join(filepath,'temp.zip')
    675     with open(fp_zip, 'wb') as fd:

File ~\.conda\envs\coastsat\lib\site-packages\requests\api.py:73, in get(url, params, **kwargs)
     62 def get(url, params=None, **kwargs):
     63     r"""Sends a GET request.
     64 
     65     :param url: URL for the new :class:`Request` object.
   (...)
     70     :rtype: requests.Response
     71     """
---> 73     return request("get", url, params=params, **kwargs)

File ~\.conda\envs\coastsat\lib\site-packages\requests\api.py:59, in request(method, url, **kwargs)
     55 # By using the 'with' statement we are sure the session is closed, thus we
     56 # avoid leaving sockets open which can trigger a ResourceWarning in some
     57 # cases, and look like a memory leak in others.
     58 with sessions.Session() as session:
---> 59     return session.request(method=method, url=url, **kwargs)

File ~\.conda\envs\coastsat\lib\site-packages\requests\sessions.py:587, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    582 send_kwargs = {
    583     "timeout": timeout,
    584     "allow_redirects": allow_redirects,
    585 }
    586 send_kwargs.update(settings)
--> 587 resp = self.send(prep, **send_kwargs)
    589 return resp

File ~\.conda\envs\coastsat\lib\site-packages\requests\sessions.py:701, in Session.send(self, request, **kwargs)
    698 start = preferred_clock()
    700 # Send the request
--> 701 r = adapter.send(request, **kwargs)
    703 # Total elapsed time of the request (approximately)
    704 elapsed = preferred_clock() - start

File ~\.conda\envs\coastsat\lib\site-packages\requests\adapters.py:547, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    544             raise
    546 except (ProtocolError, OSError) as err:
--> 547     raise ConnectionError(err, request=request)
    549 except MaxRetryError as e:
    550     if isinstance(e.reason, ConnectTimeoutError):
    551         # TODO: Remove this in 3.0.0: see #2811

ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))
```

**Comment by kvos** [comment]
I just pushed a commit on the `development` branch with a try/except loop around the download functions, it tries to download it up to 100 times to overcome timeouts and bad responses. I've been running downloads for 48h and all good so far. Try it out and let me know if it runs smoothily for you too

**Comment by Lvulis** [comment]
Testing it out now, thanks.

**Comment by Lvulis** [comment]
I think that fixed it. Got the following which seems positive. I wonder if this also addresses #301? If that continues a possibility is to use some kind of checksum utility to compare if the data being sent from GEE is correctly downloaded, would implement it myself but have poor python knowledge. 
```python
Downloading images:
L5: 481 images
7%
Download failed, trying again...
13%
Download failed, trying again...
74%
Download failed, trying again...
100%
L7: 480 images
100%
L8: 194 images
100%
S2: 792 images
100%
```

**Comment by kvos** [comment]
great, thanks for testing. Will keep it like this for the moment, if it still occurs we can re-evaluate an alternative solution
