### ISSUE TITLE
question about gcloud

### ISSUE THREAD

**Issue by oceanywalker** [kvos/CoastSat#329]
I encountered a question " 'gcloud' is not an internal or external command, nor is it a runnable program 
Or batch file." after running the following command "earthengine authenticate". 

Traceback (most recent call last):
  File "C:\Users\yinch\anaconda3\envs\coastsat\Scripts\earthengine-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\yinch\anaconda3\envs\coastsat\lib\site-packages\ee\cli\eecli.py", line 82, in main
    _run_command()
  File "C:\Users\yinch\anaconda3\envs\coastsat\lib\site-packages\ee\cli\eecli.py", line 61, in _run_command
    dispatcher.run(args, config)
  File "C:\Users\yinch\anaconda3\envs\coastsat\lib\site-packages\ee\cli\commands.py", line 355, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "C:\Users\yinch\anaconda3\envs\coastsat\lib\site-packages\ee\cli\commands.py", line 397, in run
    ee.Authenticate(**args_auth)
  File "C:\Users\yinch\anaconda3\envs\coastsat\lib\site-packages\ee\__init__.py", line 104, in Authenticate
    return oauth.authenticate(authorization_code, quiet, code_verifier, auth_mode,
  File "C:\Users\yinch\anaconda3\envs\coastsat\lib\site-packages\ee\oauth.py", line 381, in authenticate
    _load_app_default_credentials(auth_mode == 'gcloud', scopes, quiet)
  File "C:\Users\yinch\anaconda3\envs\coastsat\lib\site-packages\ee\oauth.py", line 291, in _load_app_default_credentials
    raise Exception('gcloud failed. Please check for any errors above '
Exception: gcloud failed. Please check for any errors above and install gcloud if needed.

**Comment by kvos** [comment]
you need to install gcloud. there are instructions in the readme, let me know if it still doesn't work after installing gcloud

**Comment by oceanywalker** [comment]
I have checked it several times, but I can't find the instructions about "cloud". Is it included in other packages?
![image](https://user-images.githubusercontent.com/113840651/191395260-d3db8b1e-b21c-4c70-bf29-fef0246cf875.png)

**Comment by kvos** [comment]
![image](https://user-images.githubusercontent.com/7217258/191414612-a5062f9d-d590-4065-a7ea-ca53e9db4439.png)

**Comment by oceanywalker** [comment]
I tried it, but ,,,
![image](https://user-images.githubusercontent.com/113840651/191883659-d0882db8-1826-4fde-8b9a-672ba5b40110.png)

**Comment by thallesaaa** [comment]
Try again, @oceanywalker. I just had this same gcloud problem hours ago and did just as the readme file suggests (@kvos's screenshot above) and it worked. The page might have been just temporarily unavailable - it seems to be back now.

**Comment by oceanywalker** [comment]
> 

Thanks a lot!

**Comment by oceanywalker** [comment]
@thallesaaa Thanks a lot!

**Comment by bagussatya** [comment]
Hi, I've already installed gcloud, then restarted my anaconda prompt, after that when i tried to run earthengine authenticate it says that gcloud commnad not found
