### ISSUE TITLE
Issue with GoogleEarth Engine after succesful installation and use for a few days.

### ISSUE THREAD

**Issue by simonweppe** [kvos/CoastSat#365]
Hi there @kvos  me again. I've used the package without any issues for several days and this morning got this complaint from the google earth engine

`google.auth.exceptions.RefreshError: ('invalid_scope: Bad Request', {'error': 'invalid_scope', 'error_description': 'Bad Request'})`

Tried to re run the authentification process , which went through ok

`earthengine authenticate --auth_mode=notebook`

But still unable to go past that error. I tried a fresh install in a new conda env, same issues...getting confused ! 

Any help/insights appreciated :)

**Comment by simonweppe** [comment]
Full TraceBack

```
Traceback (most recent call last):
  File "/home/simon/Documents/GitHub/CoastSat/coastsat/SDS_download.py", line 514, in check_images_available
    ee.ImageCollection('LANDSAT/LT05/C01/T1_TOA')
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/computedobject.py", line 31, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/imagecollection.py", line 41, in __init__
    self.initialize()
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/imagecollection.py", line 75, in initialize
    super(ImageCollection, cls).initialize()
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/collection.py", line 32, in initialize
    apifunction.ApiFunction.importApi(cls, 'Collection', 'Collection')
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/apifunction.py", line 183, in importApi
    cls.initialize()
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/data.py", line 1125, in getAlgorithms
    call = _get_cloud_api_resource().projects().algorithms().list(
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/data.py", line 283, in _get_cloud_api_resource
    raise ee_exception.EEException(
ee.ee_exception.EEException: Earth Engine client library not initialized. Run `ee.Initialize()`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_jupyter_TIWAI.py", line 99, in <module>
    SDS_download.check_images_available(inputs);
  File "/home/simon/Documents/GitHub/CoastSat/coastsat/SDS_download.py", line 516, in check_images_available
    ee.Initialize()
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/__init__.py", line 131, in Initialize
    data.initialize(
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/data.py", line 202, in initialize
    _install_cloud_api_resource()
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/data.py", line 261, in _install_cloud_api_resource
    _cloud_api_resource = _cloud_api_utils.build_cloud_resource(
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/_cloud_api_utils.py", line 178, in build_cloud_resource
    resource = build(static_discovery=False)
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/ee/_cloud_api_utils.py", line 162, in build
    return discovery.build(
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/googleapiclient/discovery.py", line 287, in build
    content = _retrieve_discovery_doc(
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/googleapiclient/discovery.py", line 422, in _retrieve_discovery_doc
    resp, content = req.execute(num_retries=num_retries)
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/googleapiclient/http.py", line 923, in execute
    resp, content = _retry_request(
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/google_auth_httplib2.py", line 209, in request
    self.credentials.before_request(self._request, method, uri, request_headers)
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/google/auth/credentials.py", line 135, in before_request
    self.refresh(request)
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/google/oauth2/credentials.py", line 335, in refresh
    ) = reauth.refresh_grant(
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/google/oauth2/reauth.py", line 349, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/home/simon/anaconda3/envs/coastsat3/lib/python3.8/site-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_scope: Bad Request', {'error': 'invalid_scope', 'error_description': 'Bad Request'})
```

**Comment by simonweppe** [comment]
Might have found a fix. Activate your coastsat environment 

1) delete existing file `credentials` in `/home/your_user_name/.config/earthengine`

2) update the earthengine-api
` conda update -c conda-forge earthengine-api # update earthengine`

3) rerun `earthengine authenticate --auth_mode=notebook` 
(this will save a new "credentials" file in the ~/.config/earthengine`) 

4) quit and re-activate your `coastsat` environment

**Comment by kvos** [comment]
always strange things with google earth engine activation, glad you found a way around
